Repository malcolm5858/IPRO497GroupA, pull requests merged in 2021-04, with the labels that each got.

#56 Click on buttons
  Client/course-eval/src/Components/HistogramWithData.tsx
  Client/course-eval/src/Components/Rating.tsx
  Client/course-eval/src/Components/RatingBreakdown.tsx
  Client/course-eval/src/Pages/CourseRatings.tsx
  Client/course-eval/src/Pages/TeacherRatings.tsx
  Server/index.ts
Labels: Scenario 2

#58 Survey creation page
  Client/course-eval/src/App.tsx
  Client/course-eval/src/Components/ModalRapper.tsx
  Client/course-eval/src/Pages/SurveyCreation.tsx
  Server/index.ts
Labels: Scenario 3

#65 Created a page to review survey responses
  .vscode/settings.json
  Client/course-eval/src/App.tsx
  Client/course-eval/src/Components/QuestionsAndAnswers.tsx
  Client/course-eval/src/Pages/SurveyResponses.tsx
  Server/index.ts
Labels: Scenario 3

#62 Finished survey page
  Client/course-eval/src/Components/Survey.tsx
  Server/index.ts
Labels: Scenario 1

#68 Teacher page
  Client/course-eval/package.json
  Client/course-eval/src/App.tsx
  Client/course-eval/src/Components/AddStudentRapper.tsx
  Client/course-eval/src/Components/AddSurveyRapper.tsx
  Client/course-eval/src/Pages/Launch.tsx
  Client/course-eval/src/Pages/Login.tsx
  Client/course-eval/src/Pages/SurveyCreation.tsx
  Client/course-eval/src/Pages/SurveyResponses.tsx
  Client/course-eval/src/Pages/TeacherRatings.tsx
  Client/course-eval/src/Pages/TeacherView.tsx
  Client/course-eval/yarn.lock
  Database_Documents/User_data.json
  Server/index.ts
Labels: Scenario 3
